title: UBC Library Research Commons
description: Documentation
remote_theme: ubc-library-rc/rc-workshop-template
footer_content: "<a href=\"https://github.com/ubc-library-rc/rc-docs/\">View workshop content in GitHub</a>"
